#!/usr/local/bin/zsh
# Brewster updates/ runs package managers: Homebrew (macOS), npm (Node.js), pip (Python)
{
    if read -qr "CHOICE?Press [y]es to run Brewster:  "; then
        sleep 1
        spinner() {
            slt=0.5
            printf "\033c\r${(%):-%F{green}==<${(%):-%f} running Brewster${(%):-%F{green}.  ${(%):-%f}\n"
            sleep $slt
            printf "\033c\r${(%):-%F{green}==/${(%):-%f} running Brewster${(%):-%F{green}.. ${(%):-%f}\n"
            sleep $slt
            printf "\033c\r${(%):-%F{green}==>${(%):-%f} running Brewster${(%):-%F{green}...${(%):-%f}\n"
            sleep $slt
        }
        i=0
        while [ $i -le 3 ]; do
            spinner
            i=$(($i + 1))
        done
        . /Users/syd/Code/misc/Brewster/brewster
        return 0
    else
        return 1
    fi
}
2>/dev/null
