#!/usr/local/bin/zsh
# [c]hange [d]irectory [e]nhanced runs cd then prints the dir's 10 most recent files
{ 
    DIR="$*"
    if [ $# -lt 1 ]; then
        DIR=$PWD # if no DIR given, assume $PWD (current working directory)
    fi
    builtin cd "${DIR}"
    # sort by date, descending
    ls -aFGhort    
    # clear screen, insert newline
    printf "\033c\n" 
    lsd|grep  --color=never --invert-match "dr.*" | tail -10
} 
2>/dev/null
