#!/bin/zsh

DIR=${1:-$PWD}
total=0
ejected=0

for v in /Volumes/*; do
    if [[ $v =~ (Preboot|Calvin|com\.apple\.TimeMachine) ]]; then
        continue
    else
        echo "Ejecting $v..."
        if diskutil eject "$v"; then
            ((ejected++))
        fi
    fi
    ((total++))
done

if ((total == 0)); then
    echo "No drives to eject"
else
    msg="$ejected drive(s) ejected"
    failed=$((total - ejected))
    if ((failed > 0)); then
        msg="$msg, $failed drive(s) failed to eject"
    fi
    echo "$msg"
fi

# Log the results of each run
echo "$(date +%FT%T%z): $msg" >> ~/.ejector.log

builtin cd "${DIR}" || return 1

# app     : ejector
# ver     : 2.0
# ---
# file    : ~/Code/misc/scripts/ejector.sh
# title   : Eject USB flash drives
# subject :
# author  : Syd Salmon
# company : Proganica Brand Development
# comments: updated via GPT-4
# keywords:
# ---
# GNU General Public License
# Copyright (C) 2022 Syd Salmon
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software. You are welcome to redistribute it.
# Attract good karma! Credit the author.
# ---
# https://apple.stackexchange.com/questions/370406/how-to-eject-all-drives-from-the-command-line
# ^ 2022-02-28T16:01:32-0500
# $ 2023-09-13T16:03:51-0400
