#!/bin/zsh
{
    python3 -m pip install -U autopep8
    python3 -m pip install -U gpg
    python3 -m pip install -U notmuch
    python3 -m pip install -U pip
    python3 -m pip install -U pycodestyle
    python3 -m pip install -U rfc6555
    python3 -m pip install -U selectors2
    python3 -m pip install -U setuptools
    python3 -m pip install -U toml
    python3 -m pip install -U wheel
    python3 -m pip check
} 2> /dev/null
